/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magento.last.five;

import driver.DriverCreator;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.*;

import static java.lang.Thread.sleep;

public class LumaTest {
    private WebDriver driver = null;

    @BeforeClass
    public void setup() {
        String browser = "firefox";
        driver = DriverCreator.instantiateDriver(browser);
    }

    public void loginTest() {
        LoginPage loginPage = new LoginPage(driver);
        loginPage.login();
    }
    @Test
    public void testSearchProduct() {
        SearchProduct searchProduct = new SearchProduct(driver);
        int countOfListedProducts = searchProduct.verifyListOfSearchElements("shirt");
        Assert.assertEquals(countOfListedProducts, 5);
    }

    @Test
    public void addToCartTest() {
        loginTest();
        OrderProduct order = new OrderProduct(driver);
        int initialCountOfCart  = order.AddToCart();
        System.out.println("Initial count of cart : " + initialCountOfCart);
    }

    @Test
    public void verifyCount() throws InterruptedException {
        ConfirmOrder confirmOrder = new ConfirmOrder(driver);
        int count = confirmOrder.checkCart();
        Assert.assertEquals(count, 2);
    }

    @Test
    public void testCheckoutPage() throws InterruptedException {
        CheckoutPage checkoutPage = new CheckoutPage(driver);
        checkoutPage.placeOrder();
    }

    @Test
    public void testUserAccountPage() throws InterruptedException {
        UserAccountPage userAccountPage = new UserAccountPage(driver);
        userAccountPage.editProfile();
        String items = userAccountPage.myOrders();
        Assert.assertEquals(items, "2 Item(s)");
    }

    @Test
    public void testWishListPage() {
        WishList wishList = new WishList(driver);
        int countOfItemsInWishList = wishList.verifyWishList();
        Assert.assertEquals(countOfItemsInWishList, 1);
    }

    @Test
    public void testFilterProduct(){
        FilterProduct filterProduct = new FilterProduct(driver);
        filterProduct.filterPage();
    }

    @AfterClass
    public void tearDown() {
        driver.quit();
    }

}
