/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magento.last.five;

import actions.FindElements;
import actions.PageActions;
import driver.PageWaits;
import org.openqa.selenium.By;
import data.Credentials;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import static org.openqa.selenium.By.*;


public class LoginPage {
    private WebDriver driver = null;
    public LoginPage(WebDriver driver) {
        this.driver = driver;
    }

    public void login() {

        PageActions action = PageActions.getActionsObject();
        PageWaits pageWaits = PageWaits.getPageWaitsObject(driver);
        FindElements findElements = FindElements.getInstance(driver);

        String url = "https://magento.softwaretestingboard.com/";

        action.Maximize(driver);
        action.navigateTo(driver,url);

        String signInButton = "Sign In";
        WebElement signInElement = pageWaits.waitUntilElementFoundByPartialLink(signInButton);
        action.clickElement(signInElement);

        String emailId = "email";
        WebElement emailElement = pageWaits.waitUntilElementFoundByID( emailId);
        action.enterKeys(emailElement, Credentials.emailId());

        WebElement password = findElements.findElementByID("pass");
        action.enterKeys(password,Credentials.password());

        WebElement submitButtonElement = findElements.findElementByClass("primary");
        action.clickElement(submitButtonElement);

    }
}
